blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/orgs/QuillORM/discussions
    about: Please ask and answer questions and discuss here.
  - name: Core Issues
    url: https://github.com/QuillORM/core/issues/new
    about: Issues regarding the core of QuillORM belong here.
  - name: Gradle Plugin Issues
    url: https://github.com/QuillORM/gradle-plugin/issues/new
    about: Issues regarding the gradle plugin belong here.
